
VERILOG_SOURCES = $(PWD)/../top_level.v $(PWD)/../ALU.v $(PWD)/../Instruction_Cycle.v $(PWD)/../verification/ram_memory.v $(PWD)/../verification/rom_memory.v
TOPLEVEL= uproc_8bits
MODULE= uproc_8bits
EXTRA_ARGS= -I../
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
